
```{r}
library("ggplot2")
library(caret)
heart <- read.csv(file="/Users/christian.willmann/Desktop/heart.csv")
heart$ID <- seq.int(nrow(heart))
heart<-heart[,c(ncol(heart),1:(ncol(heart)-1))]
heart
```


```{r}
#Beschreibung des Datensatzes und er Attribute
#Werteräume/Datentypen/wie viele Datensätze u. Attribute
```

```{r}
#Verteilungen (Plots bspw. Weiblich Männlich/Alter, Schiefe der Werte, Streuungsmaß)
ggplot(heart, aes(x=as.factor(Sex), y=Age)) + 
    geom_boxplot(fill="slateblue", alpha=0.2) + 
    xlab("Sex")
#Häufigkeiten, Mittelwert, Median und Modus (Modus auch für Zeilattribute)
```

```{r}
#NULL-Handling
print("Checking if there is NULL Values in the Dataset!")
apply(heart, 2, function(x) any(is.na(x)))
```

```{r}
#NoiseHandling
```

```{r}
#Ausreißer via Boxplots & Isolation Forest
```

```{r}
#FeatureSelection with low 
print("Check whether an attribute has low variance (threshold), since there is no variance -> no information!")
#Sehr wenige eindeutige Werte in Bezug auf die Anzahl der Stichproben und das Verhältnis der Häufigkeit des häufigsten Wertes zum Häufigkeit des zweithäufigsten Wertes ist groß.HIER WERDEN DEFAULT WERTE GENUTZT: Frequenzschnitt = 95/5, uniqueCut = 10, saveMetrics = FALSE, Namen = FALSCH, foreach = FALSCH, allowParallel = WAHR
names(heart)[nearZeroVar(heart)]
summary(heart)
str(heart)
```

```{r}
#install.packages('pheatmap') # if not installed already
library("tidyverse")
library("ggplot2")
library("pheatmap")
## make data
heart <- read.csv(file="/Users/christian.willmann/Desktop/heart.csv")
heart$Sex <- as.numeric(c("M" = 0, "F" = 1)[heart$Sex])
heart$ChestPainType <- as.numeric(c("ATA" = 0, "NAP" = 1, "ASY" = 2, "TA" = 3)[heart$ChestPainType])
heart$RestingECG <- as.numeric(c("Normal" = 0, "ST" = 1, "LVH" = 2)[heart$RestingECG])
heart$ExerciseAngina <- as.numeric(c("N" = 0, "Y" = 1)[heart$ExerciseAngina])
heart$ST_Slope <- as.numeric(c("Up" = 0, "Flat" = 1, "Down" = 2))
heart_DepOnCorr<-subset(heart, select = -c(ST_Slope))
heart_DepOnCorr<-subset(heart_DepOnCorr, select = -c(RestingECG))
heart_DepOnCorr<-subset(heart_DepOnCorr, select = -c(RestingBP))
heart_FULL_Matrix <- cor(as.matrix(heart))
heart_Corr_Matrix <- cor(as.matrix(heart_DepOnCorr))
pheatmap(heart_FULL_Matrix, display_numbers = T, cluster_rows=F, cluster_cols=F)
pheatmap(heart_Corr_Matrix, display_numbers = T, cluster_rows=F, cluster_cols=F)
```


  
