

```{r}
library("ggplot2")
library(caret)
heart <- read.csv(file="/Users/christian.willmann/Desktop/heart.csv")
heart$ID <- seq.int(nrow(heart))
heart<-heart[,c(ncol(heart),1:(ncol(heart)-1))]
heart
```


```{r}
#Beschreibung des Datensatzes und er Attribute
#Werteräume/Datentypen/wie viele Datensätze u. Attribute
```

```{r}
#Verteilungen (Plots bspw. Weiblich Männlich/Alter, Schiefe der Werte, Streuungsmaß)
ggplot(heart, aes(x=as.factor(Sex), y=Age)) + 
    geom_boxplot(fill="slateblue", alpha=0.2) + 
    xlab("Sex")
#Häufigkeiten, Mittelwert, Median und Modus (Modus auch für Zeilattribute)
```

```{r}
#NULL-Handling
print("Checking if there is NULL Values in the Dataset!")
apply(heart, 2, function(x) any(is.na(x)))
```

```{r}
#NoiseHandling
```

```{r}
#Ausreißer via Boxplots & Isolation Forest
```

```{r}
#FeatureSelection with low 
print("Check whether an attribute has low variance (threshold), since there is no variance -> no information!")
#Sehr wenige eindeutige Werte in Bezug auf die Anzahl der Stichproben und das Verhältnis der Häufigkeit des häufigsten Wertes zum Häufigkeit des zweithäufigsten Wertes ist groß.HIER WERDEN DEFAULT WERTE GENUTZT: Frequenzschnitt = 95/5, uniqueCut = 10, saveMetrics = FALSE, Namen = FALSCH, foreach = FALSCH, allowParallel = WAHR
names(heart)[nearZeroVar(heart)]
summary(heart)
str(heart)
```


  
