
```{r}
library("ggplot2")
library(caret)
heart <- read.csv(file="/Users/christian.willmann/Desktop/heart.csv")
heart$ID <- seq.int(nrow(heart))
heart<-heart[,c(ncol(heart),1:(ncol(heart)-1))]
heart
trueHeart<- heart
```


```{r}
#Beschreibung des Datensatzes und er Attribute


#import statistics as stat
#g1 = df_enc['G1']
#modeg1 = stat.mode(g1)
#print ('Modus der Zwischennote (G1):', modeg1)
names(heart)
str(heart)

#Werteräume/Datentypen/wie viele Datensätze u. Attribute
#Mean Median Quantile 
#Häufigkeiten, Mittelwert, Median und Modus (Modus auch für Zielattribute)
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

```{r}
#Verteilungen (Plots bspw. Weiblich Männlich/Alter, Schiefe der Werte, Streuungsmaß)
#Ausreißer via Boxplots & Isolation Forest
print(colnames(heart))
ggplot(heart, aes(x=as.factor(Sex), y=Age)) + 
    geom_boxplot(fill="slateblue", alpha=0.2) + 
    xlab("Sex")
ggplot(heart, aes(x=as.factor(Sex), y=RestingBP)) + 
    geom_boxplot(fill="slateblue", alpha=0.2) + 
    xlab("Sex")
ggplot(heart, aes(x=as.factor(Sex), y=Cholesterol)) + 
    geom_boxplot(fill="slateblue", alpha=0.2) + 
    xlab("Sex")
ggplot(heart, aes(x=as.factor(Sex), y=FastingBS)) + 
    geom_boxplot(fill="slateblue", alpha=0.2) + 
    xlab("Sex")
ggplot(heart, aes(x=as.factor(Sex), y=MaxHR)) + 
    geom_boxplot(fill="slateblue", alpha=0.2) + 
    xlab("Sex")
ggplot(heart, aes(x=as.factor(Sex), y=Oldpeak)) + 
    geom_boxplot(fill="slateblue", alpha=0.2) + 
    xlab("Sex")

### 2. Schritt: Spalten mit Character in Numerics umwandeln (Sex, ChestPainType, RestingECG, ExerciseAngina, ST_Slope)
### https://stackoverflow.com/questions/47857066/replace-characters-in-a-column-with-numbers-r
heart$ChestPainType <- as.numeric(c("ATA" = 0, "NAP" = 1, "ASY" = 2, "TA" = 3)[heart$ChestPainType])
heart$RestingECG <- as.numeric(c("Normal" = 0, "ST" = 1, "LVH" = 2)[heart$RestingECG])
heart$ExerciseAngina <- as.numeric(c("N" = 0, "Y" = 1)[heart$ExerciseAngina])
heart$ST_Slope <- as.numeric(c("Up" = 0, "Flat" = 1, "Down" = 2))

ggplot(heart, aes(x=as.factor(Sex), y=ChestPainType)) + 
    geom_boxplot(fill="slateblue", alpha=0.2) + 
    xlab("Sex")
ggplot(heart, aes(x=as.factor(Sex), y=RestingECG)) + 
    geom_boxplot(fill="slateblue", alpha=0.2) + 
    xlab("Sex")
ggplot(heart, aes(x=as.factor(Sex), y=ExerciseAngina)) + 
    geom_boxplot(fill="slateblue", alpha=0.2) + 
    xlab("Sex")
ggplot(heart, aes(x=as.factor(Sex), y=ST_Slope)) + 
    geom_boxplot(fill="slateblue", alpha=0.2) + 
    xlab("Sex")
```
```{r}
library("ggplot2")
library("dplyr")
library("tidyr")
heart
ggplot(data=trueHeart, aes(x=Age, group=ChestPainType, fill=ChestPainType)) +
    geom_density(adjust=1, alpha=.4) +
    facet_wrap(~Sex) +
    theme(
      panel.spacing = unit(0.1, "lines"),
      axis.ticks.x=element_blank()
    )
ggplot(data=trueHeart, aes(x=Age, group=RestingECG, fill=RestingECG)) +
    geom_density(adjust=1, alpha=.4) +
    facet_wrap(~Sex) +
    theme(
      panel.spacing = unit(0.1, "lines"),
      axis.ticks.x=element_blank()
    )
ggplot(data=trueHeart, aes(x=Age, group=ExerciseAngina, fill=ExerciseAngina)) +
    geom_density(adjust=1, alpha=.4) +
    facet_wrap(~Sex) +
    theme(
      panel.spacing = unit(0.1, "lines"),
      axis.ticks.x=element_blank()
    )
ggplot(data=trueHeart, aes(x=Age, group=ST_Slope, fill=ST_Slope)) +
    geom_density(adjust=1, alpha=.4) +
    facet_wrap(~Sex) +
    theme(
      panel.spacing = unit(0.1, "lines"),
      axis.ticks.x=element_blank()
    )
    
ggplot(data=trueHeart, aes(x=Age, group=HeartDisease, fill=HeartDisease)) +
    geom_density(adjust=1, alpha=.4) +
    facet_wrap(~Sex) +
    theme(
      panel.spacing = unit(0.1, "lines"),
      axis.ticks.x=element_blank()
    )
```

```{r}
#FeatureSelection with low 
print("Check whether an attribute has low variance (threshold), since there is no variance -> no information!")
#Sehr wenige eindeutige Werte in Bezug auf die Anzahl der Stichproben und das Verhältnis der Häufigkeit des häufigsten Wertes zum Häufigkeit des zweithäufigsten Wertes ist groß.HIER WERDEN DEFAULT WERTE GENUTZT: Frequenzschnitt = 95/5, uniqueCut = 10, saveMetrics = FALSE, Namen = FALSCH, foreach = FALSCH, allowParallel = WAHR
names(trueHeart)[nearZeroVar(heart)]
summary(trueHeart)
str(trueHeart)

```

```{r}
#install.packages('pheatmap') # if not installed already
library("tidyverse")
library("ggplot2")
library("pheatmap")
## make data
heart <- read.csv(file="/Users/christian.willmann/Desktop/heart.csv")
heart$Sex <- as.numeric(c("M" = 0, "F" = 1)[heart$Sex])
heart$ChestPainType <- as.numeric(c("ATA" = 0, "NAP" = 1, "ASY" = 2, "TA" = 3)[heart$ChestPainType])
heart$RestingECG <- as.numeric(c("Normal" = 0, "ST" = 1, "LVH" = 2)[heart$RestingECG])
heart$ExerciseAngina <- as.numeric(c("N" = 0, "Y" = 1)[heart$ExerciseAngina])
heart$ST_Slope <- as.numeric(c("Up" = 0, "Flat" = 1, "Down" = 2))

heart_FULL_Matrix <- cor(as.matrix(heart))
heart_Corr_Matrix <- cor(as.matrix(heart_DepOnCorr))
pheatmap(heart_FULL_Matrix, display_numbers = T, cluster_rows=F, cluster_cols=F)
pheatmap(heart_Corr_Matrix, display_numbers = T, cluster_rows=F, cluster_cols=F)
```



```{r}
#Data Preparation

#NULL-Handling
print("Checking if there is NULL Values in the Dataset!")
apply(heart_DepOnCorr, 2, function(x) any(is.na(x)))
```

```{r message=TRUE, paged.print=TRUE}
#Ausreißer/0 Wert entfernen in RestingBlut Pressure
#https://www.kaggle.com/fedesoriano/heart-failure-prediction/discussion/286659
print(heart_DepOnCorr[450,])
heart<-heart_DepOnCorr[-450,]

trueHeart<-trueHeart[-450,]
#Cholestorol with 0(female)
heart_CholesterolEqualZero <- subset(heart_DepOnCorr, Cholesterol==0)
heart_CholesterolEqualZero
#Wegen hoher Anzahl an falsch aufgenommener Cholesterinwerte und einer Korrelation von -0,23, wird das Feature entfert
heart_selected<-subset(heart_DepOnCorr, select = -c(Cholesterol))
heart_selected

trueHeart<- subset(trueHeart, select = -c(Cholesterol))
trueHeart
```



<!-- ### 2. Schritt: Spalten mit Character in Numerics umwandeln (Sex, ChestPainType, RestingECG, ExerciseAngina, ST_Slope) -->
<!-- ### https://stackoverflow.com/questions/47857066/replace-characters-in-a-column-with-numbers-r -->
<!-- heart$ChestPainType <- as.numeric(c("ATA" = 0, "NAP" = 1, "ASY" = 2, "TA" = 3)[heart$ChestPainType]) -->
<!-- heart$RestingECG <- as.numeric(c("Normal" = 0, "ST" = 1, "LVH" = 2)[heart$RestingECG]) -->
<!-- heart$ExerciseAngina <- as.numeric(c("N" = 0, "Y" = 1)[heart$ExerciseAngina]) -->
<!-- heart$ST_Slope <- as.numeric(c("Up" = 0, "Flat" = 1, "Down" = 2)) -->

