---
title: "BayesModel"
output: html_document
---

```{r}
#Hier sollte man umschalten können zwischen heart undd trueHeart (also bereinigt und nicht bereinigt)
heart <- read.csv(file="/Users/christian.willmann/Desktop/heart.csv")
heart$ID <- seq.int(nrow(heart))
heart<-heart[,c(ncol(heart),1:(ncol(heart)-1))]
heart
#Subsetting without Cholesterol and the Data which has RestingBP = 0
trueHeart<-subset(heart, select = -c(Cholesterol))
trueHeart<-trueHeart[-450,]
trueHeart
```

```{r}
#Hier ein Slider um die Bins zu bestimmen
apply(trueHeart, 2, function(x) any(is.na(x)))
summary(trueHeart)
str(trueHeart)

#Trennen der Variablen von den Ziellabel
heartVariables <- trueHeart


#Changing Age in characters
column <- 2
mini<-min(heartVariables[,column])
maxi<-max(heartVariables[,column])
span<-maxi-mini
breaks<- 10
steps<-span/breaks
bins <- c(mini-1)
for(i in 1:breaks){
    bins <- c(bins,(mini+i*steps))
    }
#DF clearen
bin_names <- c(paste0(mini,"-",mini+steps)) 
for(i in 1:(breaks-1)){
    bin_names <- c(bin_names,paste0(mini+i*steps,"-",mini+(i+1)*steps)) 
    }
bin_names
heartVariables$Age <- cut(heartVariables$Age, breaks = bins, labels = bin_names)
summary(heartVariables$Age)
plot(heartVariables$Age)

breakfunction <- function(indexCol, breakings)
  column <- indexCol
  mini<-min(heartVariables[,column])
  maxi<-max(heartVariables[,column])
  span<-maxi-mini
  breaks<- breakings
  steps<-span/breaks
  bins <- c(mini-1)
  for(i in 1:breaks){
      bins <- c(bins,(mini+i*steps)) 
      }
  #DF clearen
  bin_names <- c(paste0(mini,"-",mini+steps)) 
  for(i in 1:(breaks-1)){
      bin_names <- c(bin_names,paste0(mini+i*steps,"-",mini+(i+1)*steps)) 
      }
  bin_names
  heartVariables$RestingBP <- cut(heartVariables$RestingBP, breaks = bins, labels = bin_names)
  summary(heartVariables$RestingBP)
  diagramm<-plot(heartVariables$RestingBP)
  return(diagramm)


column <- 8
mini<-min(heartVariables[,column])
maxi<-max(heartVariables[,column])
span<-maxi-mini
breaks<- 10
steps<-span/breaks
bins <- c(mini-1)
for(i in 1:breaks){
    bins <- c(bins,(mini+i*steps)) 
    }
#DF clearen
bin_names <- c(paste0(mini,"-",mini+steps)) 
for(i in 1:(breaks-1)){
    bin_names <- c(bin_names,paste0(mini+i*steps,"-",mini+(i+1)*steps)) 
    }
bin_names

heartVariables$MaxHR <- cut(heartVariables$MaxHR, breaks = bins, labels = bin_names)
summary(heartVariables$MaxHR)
plot(heartVariables$MaxHR)

column <- 10

mini<-min(heartVariables[,column])
maxi<-max(heartVariables[,column])
span<-maxi-mini
breaks<- 10
steps<-span/breaks
bins <- c(mini-1)
for(i in 1:breaks){
    bins <- c(bins,(mini+i*steps)) 
    }
#DF clearen
bin_names <- c(paste0(mini,"-",mini+steps)) 
for(i in 1:(breaks-1)){
    bin_names <- c(bin_names,paste0(mini+i*steps,"-",mini+(i+1)*steps)) 
    }
bin_names

heartVariables$Oldpeak <- cut(heartVariables$Oldpeak, breaks = bins, labels = bin_names)
summary(heartVariables$Oldpeak)
plot(heartVariables$Oldpeak)

heart

```

```{r setup, include=FALSE}
#Counts & Probabilitys
#install.packages("tibble")
library(tibble)
getProbsStuff<-function(Datensatz ,column){
  print(paste("Counts to every feature value of", colnames(Datensatz[column])))
  counts<- table(Datensatz[column])
  print(counts)
  print(paste("Probabilytis to every feature value of", colnames(Datensatz[column])))
  probs<-((table(Datensatz[column])/nrow(Datensatz))*100)
  NOTprobs<-(100-((table(Datensatz[column])/nrow(Datensatz))*100))
  print(probs)
  headers<- names(counts)
  concs<-data_frame(headers,counts,probs,NOTprobs)
  return(concs)
}
conc<-getProbsStuff(heartVariables,8)
#Unabhängikeits annahme !!!!!!!!!!!!!!!!!!!!!
#WENN EIN FEHLER AM ENDE KOMMT IST DAS EGAL. DADURCH WERDEN DIE TABLE HIER BESSER ANGEZEIGT.
```



```{r}
#Balkendiagramm mit den Wahrscheinlichkeiten
#Hier nur ein Feature, vl ist des einfacher
#install.packages("rpart")
library(rpart)
binary.model <-rpart(HeartDisease ~ ., data = trueHeart, cp = .02)
plot(binary.model)

#plot(concs,uniform= T, compress=T,branch=0,7)

```
```{r}
survived <- rpart(HeartDisease ~ ., data = ptitanic, cp = .02)
rpart.plot(survived, type = 3, clip.right.labs = FALSE, branch = .3, under = TRUE)
rpart.rules(survived, cover = TRUE)
```
 
```{r}
heartVariables
heart_AgeInBorder <- subset(heartVariables, heartVariables[2]!="72.1-77")
heart_AgeInBorder
concTRUE<-getProbsStuff(heart_AgeInBorder,12)
view(heart_AgeInBorder)
concTRUE$probs[1]

```


```{r}
library(readxl)
#X represents an HeartDisease=1 
computeBayes<- function(P_X_value,P_value,P_X_NOTvalue,P_NOTvalue){
  print(paste("P(1/value)",P_X_value))
  print(paste("P(value)",P_value))
  print(paste("P(1/NOTvalue)",P_X_NOTvalue))
  print(paste("P(NOTvalue)",P_NOTvalue))
  #Formel to compute the Bayes
  P_value_X<-((P_X_value*P_value)/((P_X_value*P_value)+(P_X_NOTvalue*P_NOTvalue))*100)
  return (signif(P_value_X,6))
}


getDATAforBayes <-function(path,colNUM){
  bins <- c()
  headers<- c()
  C_P <- read_excel(path)
  for(rangeOFvalue in C_P$headers){
    #Subset Heart to get the Column
    SUBofValue <- subset(heartVariables, heartVariables[colNUM]==rangeOFvalue)
    NOTinValueRange<-subset(heartVariables, heartVariables[colNUM]!=rangeOFvalue)
    conclusion<-getProbsStuff(SUBofValue,12)
    conclusion4NOTinRange<-getProbsStuff(NOTinValueRange,12)
    #Subset the whole, to get the Prob. of each Value
    ConcValueLine <- subset(C_P, headers==rangeOFvalue)
    bin<-computeBayes(conclusion$probs[2],ConcValueLine$probs[1],conclusion4NOTinRange$probs[2],ConcValueLine$NOTprobs[1])
    bins <- c(bins,bin)
    head<- rangeOFvalue
    headers <- c(headers,head)
  }
  names(bins)<- headers

  view(bins)
  xxy<-barplot(height = bins, las=2,5, cex.names=.9,col = rainbow(20),ylim=c(0,50))
  text(x = xxy, y = bins, label = bins, pos = 3, cex = 0.8, col = "red")
}
getDATAforBayes("/Users/christian.willmann/Documents/Shiny-Visualisierung/BayesModel/Counts&Probabilitys/C&P_Age.xlsx", 2)

#https://stackoverflow.com/questions/16121903/r-barplot-y-axis-scale-too-short
#https://swcarpentry.github.io/r-novice-inflammation/02-func-R/

```
 
 

<!-- ```{r cars} -->
<!-- #Trennen der Variablen von den Ziellabel -->
<!-- #TRAIN TEST SPLIT!!!!!!!!!!!!! -->
<!-- heartVariables <- heart[,1:12] # Selecting the first 13 colums as variables -->
<!-- heartVariables -->

<!-- heartDiseasePrediction <- rbind(heart[,13:13],heart[,1:1])# Selecting the last Column as Prediction -->
<!-- heartDiseasePrediction<-t(heartDiseasePrediction) -->
<!-- heartDiseasePrediction<-heartDiseasePrediction[,c(ncol(heartDiseasePrediction),1:(ncol(heartDiseasePrediction)-1))] -->
<!-- colnames(heartDiseasePrediction) <- c("ID", "heartDiseasePrediction") -->
<!-- heartDiseasePrediction -->

<!-- ``` -->



<!-- ```{r pressure, echo=FALSE} -->
<!-- plot(pressure) -->
<!-- ``` -->

